spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/secure_file_upload}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
app:
  upload:
    directory: ${UPLOAD_DIRECTORY:./uploads}
server:
  port: ${PORT:8080}
  error:
    include-message: never
