CREATE TABLE file_extension_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extension VARCHAR(20) NOT NULL,
    policy_type VARCHAR(10) NOT NULL,
    blocked BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_file_extension_policy_extension UNIQUE (extension),
    CONSTRAINT ck_file_extension_policy_type CHECK (policy_type IN ('FIXED', 'CUSTOM'))
);

INSERT INTO file_extension_policy (extension, policy_type, blocked) VALUES
    ('bat', 'FIXED', FALSE), ('cmd', 'FIXED', FALSE), ('com', 'FIXED', FALSE),
    ('cpl', 'FIXED', FALSE), ('exe', 'FIXED', FALSE), ('scr', 'FIXED', FALSE), ('js', 'FIXED', FALSE);
